title: Australian AI Safety Forum 2024
description: Charting Australia's Course in AI Safety and Governance. November 2024, Sydney, Australia.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman