title: Australian AI Safety Forum 2024
description: A meeting of leading scientists, policy makers, and industry leaders to discuss the future of AI safety.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman