title: Australian AI Safety Forum 2024
description: The Australian AI Safety Forum 2024 will be held in November 2024 at the Sydney Knowledge Hub at the University of Sydney. 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman