title: Australian AI Safety Forum 2024
description: Charting Australia's course in AI Safety and Governance.
 7th-8th November 2024, Sydney, Australia.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman